### PR TITLE
Return and throw tags for method php doc

### PR DESCRIPTION
**Pull request by digitalcrab**

### CODE REVIEW

**Comment by gnugat** [comment]
That was quick, thanks!
For now the tests are failing because the corresponding models aren't released, so we'll just need to wait.

**Comment by gnugat** [comment]
Ha ha, I've released v1.1 with a mention to this addition, but I forgot to actually merge the PR. I'll do it now and release a `v1.1.1`

**Comment by digitalcrab** [comment]
Thank you much! ;)

**Comment by gnugat** [comment]
By the way @fromYukki, if you're using Memio I'd be glad to know your use cases. If it's in an open source project I'd really like to see the sources and how it's used :)

**Pull request merged**
